name: Publish endstech_shared package

on:
  push:
    paths:
      - 'setup.py'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      if: contains(github.event.head_commit.message, 'Bump version number')
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      if: contains(github.event.head_commit.message, 'Bump version number')
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      if: contains(github.event.head_commit.message, 'Bump version number')
      run: python -m build
    - name: Publish package
      if: contains(github.event.head_commit.message, 'Bump version number')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}